name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Install Dependecies
      run: sudo apt install tree
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: List Files & Folders
      run: tree
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
           build/libs/DracoLoader-main-SNAPSHOT.jar
